apiVersion: v1
kind: Service
metadata:
  name: spring-test-app-service
spec:
  type: NodePort
  selector:
    app: spring-test-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000 
